# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wipe_pedigrees <- function(pedigrees) {
    invisible(.Call('popr_wipe_pedigrees', PACKAGE = 'popr', pedigrees))
}

#' Build pedigrees
#' 
#' @export
build_pedigrees <- function(population, progress = TRUE) {
    .Call('popr_build_pedigrees', PACKAGE = 'popr', population, progress)
}

#' Build kd-tree with all individuals from population
#' 
#' @export
build_kdtree_from_population <- function(population, max_leaf_size) {
    .Call('popr_build_kdtree_from_population', PACKAGE = 'popr', population, max_leaf_size)
}

#' Build kd-tree with all individuals from pedigree
#' 
#' @export
build_kdtree_from_pedigree <- function(pedigree, max_leaf_size) {
    .Call('popr_build_kdtree_from_pedigree', PACKAGE = 'popr', pedigree, max_leaf_size)
}

#' Build kd-tree from a list of pids
#' 
#' @export
build_kdtree_from_pids <- function(pids, population, max_leaf_size) {
    .Call('popr_build_kdtree_from_pids', PACKAGE = 'popr', pids, population, max_leaf_size)
}

analyse_meioses_search_tree <- function(population, search_tree, pids, radii, report_progress = FALSE) {
    .Call('popr_analyse_meioses_search_tree', PACKAGE = 'popr', population, search_tree, pids, radii, report_progress)
}

get_pids_within_radius <- function(ind, search_tree, radius) {
    .Call('popr_get_pids_within_radius', PACKAGE = 'popr', ind, search_tree, radius)
}

radius_search_count <- function(population, search_tree, pids, radii, report_progress = FALSE) {
    .Call('popr_radius_search_count', PACKAGE = 'popr', population, search_tree, pids, radii, report_progress)
}

wipe_population <- function(population) {
    invisible(.Call('popr_wipe_population', PACKAGE = 'popr', population))
}

#' Construct a population
#' 
#' @export
load_individuals <- function(pid, is_male, pid_mom, pid_dad, etrs89e = as.numeric( c()), etrs89n = as.numeric( c()), progress = TRUE, error_on_gender_mismatch = TRUE) {
    .Call('popr_load_individuals', PACKAGE = 'popr', pid, is_male, pid_mom, pid_dad, etrs89e, etrs89n, progress, error_on_gender_mismatch)
}

pop_size <- function(population) {
    .Call('popr_pop_size', PACKAGE = 'popr', population)
}

#' Get number of children for each individual in the population
#' 
#' @export
get_number_of_children <- function(population, progress = TRUE) {
    .Call('popr_get_number_of_children', PACKAGE = 'popr', population, progress)
}

popr_test <- function() {
    invisible(.Call('popr_popr_test', PACKAGE = 'popr'))
}

#' Get number of pedigrees
#' 
#' @export
pedigrees_count <- function(pedigrees) {
    .Call('popr_pedigrees_count', PACKAGE = 'popr', pedigrees)
}

#' Get pedigree size
#' 
#' @export
pedigree_size <- function(ped) {
    .Call('popr_pedigree_size', PACKAGE = 'popr', ped)
}

pedigrees_table <- function(pedigrees) {
    .Call('popr_pedigrees_table', PACKAGE = 'popr', pedigrees)
}

get_pedigree <- function(pedigrees, index) {
    .Call('popr_get_pedigree', PACKAGE = 'popr', pedigrees, index)
}

get_individual <- function(population, pid) {
    .Call('popr_get_individual', PACKAGE = 'popr', population, pid)
}

print_individual <- function(individual) {
    invisible(.Call('popr_print_individual', PACKAGE = 'popr', individual))
}

print_pedigree <- function(ped) {
    invisible(.Call('popr_print_pedigree', PACKAGE = 'popr', ped))
}

#' Build pedigrees
#' 
#' @export
get_pids_in_pedigree <- function(ped) {
    .Call('popr_get_pids_in_pedigree', PACKAGE = 'popr', ped)
}

get_pedigree_edgelist <- function(ped) {
    .Call('popr_get_pedigree_edgelist', PACKAGE = 'popr', ped)
}

#' Get pedigree information as graph (mainly intended for plotting)
#' 
#' @export
get_pedigree_as_graph <- function(ped) {
    .Call('popr_get_pedigree_as_graph', PACKAGE = 'popr', ped)
}

meiosis_dist_tree <- function(src, dest) {
    .Call('popr_meiosis_dist_tree', PACKAGE = 'popr', src, dest)
}

meiosis_dist_tree_matrix <- function(ped) {
    .Call('popr_meiosis_dist_tree_matrix', PACKAGE = 'popr', ped)
}

get_pedigree_from_individual <- function(individual) {
    .Call('popr_get_pedigree_from_individual', PACKAGE = 'popr', individual)
}

#' Get pedigree id from pid
#' 
#' @export
get_pedigree_id_from_pid <- function(population, pids) {
    .Call('popr_get_pedigree_id_from_pid', PACKAGE = 'popr', population, pids)
}

